### ISSUE TITLE
User name or password error

### ISSUE THREAD

**Issue by lc-c** [kmaster/better-mybatis-generator#1]
数据库用户和密码是正确的
总是提示User name or password error

**Comment by kmaster** [comment]
mysql还是oracle？还是其他数据库？

**Comment by jiangbianyiye** [comment]
同样的问题 mysql数据库

**Comment by kmaster** [comment]
已经添加了mysql8的驱动。

**Comment by PataPon666** [comment]
idea 选择哪个版本的驱动

**Comment by PataPon666** [comment]
数据库8.02还是报这个错误

**Comment by kmaster** [comment]
idea本身使用的驱动是com.mysql.jdbc.Driver。现在对于mysql已经取消使用idea中提供的驱动，而是com.mysql.cj.jdbc.Driver。应该能解决mysql和mysql8 这2中数据库连接失败的错误。如仍有错误请反馈，将考虑添加数据库类型的配置选择项来解决。

**Comment by ncworm** [comment]
mysql 8.0.12 报这个错误

**Comment by kmaster** [comment]
> mysql 8.0.12 报这个错误

![image](https://user-images.githubusercontent.com/17524110/45873094-32e66600-bdc4-11e8-9714-42fee37aac59.png)
版本是1.5.2吗？ 这个版本还在审核中，插件库暂时还下载不了。 可以从这个地址下载https://github.com/kmaster/better-mybatis-generator/blob/master/better-mybatis-generator.zip 
我本地测试可以连接mysql8

**Comment by ncworm** [comment]
![232323](https://user-images.githubusercontent.com/10293741/45873528-4ba34b80-bdc5-11e8-9921-80bf0fa64e24.png)
![33434343](https://user-images.githubusercontent.com/10293741/45873534-4f36d280-bdc5-11e8-998b-633399ccb5af.png)

**Comment by GimoXie** [comment]
mysql 5.7 报这个错0 0

**Comment by sk163** [comment]
![image](https://user-images.githubusercontent.com/2271609/46085550-d8d90c80-c1d8-11e8-947b-7fa7fb51c5cf.png)
1.5.2版本，mac os，mysql 5.6，输入密码后，长时间无响应，然后报error

**Comment by kmaster** [comment]
更新了1.5.3  添加了mysql8勾选项来解决mysql 和mysql8的驱动冲突  mysql8已经在url上添加?serverTimezone=UTC，如果仍不能连接，考虑设置数据库的时区（正式的生成库请谨慎设置）。

**Comment by ncworm** [comment]
![image](https://user-images.githubusercontent.com/10293741/46182501-cd800100-c2fe-11e8-857d-934fbb148394.png)

![image](https://user-images.githubusercontent.com/10293741/46182337-cc020900-c2fd-11e8-8058-98156e67990b.png)

**Comment by kmaster** [comment]
![image](https://user-images.githubusercontent.com/17524110/46182939-0b7e2480-c301-11e8-98cc-a6381fa88980.png)
现在添加了mysql8选项来区分  你是否有勾选mysql的选项。

**Comment by ncworm** [comment]
嗯，有勾选的

**Comment by kmaster** [comment]
access denied应该是账号密码的问题：
![image](https://user-images.githubusercontent.com/17524110/46183768-0c18ba00-c305-11e8-9c8d-564a3fe95dba.png)
你试下把项目路径.idea文件夹的这个插件的配置文件删除了重新连。

**Comment by ncworm** [comment]
![Uploading image.png…]()
删除测试还是不行，上面那个‘root’@'locahost' 是不是取错呢，不应该是用户名@而是用数据库名@

**Comment by kmaster** [comment]
'root'@'locahost' 这个能截图看下吗？正常的是这样
![image](https://user-images.githubusercontent.com/17524110/46241253-45762600-c3e8-11e8-9364-4cf1b046f4e8.png)
