### ISSUE TITLE
建议在读取密码为空时候重新弹出输入密码框

### ISSUE THREAD

**Issue by edoc1991** [kmaster/better-mybatis-generator#11]
大约就是遇到了bug，如果开了多个idea界面，大概是开关了一些界面后获取到的password为空（没有具体研究过idea 插件，不是很懂具体原因）
所以建议在cn.kt.generate.Generate#buildJdbcConfig函数中增加如下判断
`            String password = PasswordSafe.getInstance().getPassword(attributes_get);
            if(StringUtils.isEmpty(password)){
                new UserUI(driverClass, url, anActionEvent, config);
                return null;
            }
`
emmmmm大概就是这样。

**Comment by kmaster** [comment]
![image](https://user-images.githubusercontent.com/17524110/50441597-6a6e2c80-0936-11e9-870b-619927d1bbbb.png)
账号密码是存在密码管理器的，密码为空可能是存或取失败，关掉idea窗口按理说应该影响不到。
不过我觉得加这个判断好些，已经上传代码和zip，麻烦帮忙验证一下是否可以解决此问题，thanks。

**Comment by edoc1991** [comment]
@kmaster 
已经OK了~~~~~
