### ISSUE TITLE
【建议】添加gradle项目的支持

### ISSUE THREAD

**Issue by chenquan** [kmaster/better-mybatis-generator#18]
我发现只有使用MVN构建的项目才能正常使用，但是使用gradle的项目就无法使用

**Comment by chenquan** [comment]
@kmaster 请问会有这个添加计划吗？？

**Comment by surfsun** [comment]
没有使用过gradle，暂时没有这个添加计划

**Comment by chenquan** [comment]
> 没有使用过gradle，暂时没有这个添加计划

thanks.
