### ISSUE TITLE
gene-plugin-1.0-SNAPSHOT.jar这个包是楼主自己的还是那里的

### ISSUE THREAD

**Issue by hanjiangjiaolong** [kmaster/better-mybatis-generator#20]
gene-plugin-1.0-SNAPSHOT.jar这个包是楼主自己的还是那里的

**Comment by surfsun** [comment]
jar包自己封装了 类采用了其他开源项目。

**Comment by hanjiangjiaolong** [comment]
能不能提供下这个jar的源码，我想自己做一些修改以及改造

**Comment by surfsun** [comment]
之前的工程找不到了 重新做了下 已上传。https://github.com/kmaster/geneplugin  。打了jar包之后进行替换即可。

**Comment by hanjiangjiaolong** [comment]
thank you
