### ISSUE TITLE
数据库用户名密码修改过后，插件的需要的用户名密码无法更新，导致生成文件失败

### ISSUE THREAD

**Issue by NeighborOldKing** [kmaster/better-mybatis-generator#21]
数据库用户名密码修改过后，插件的需要的用户名密码无法更新，导致生成文件失败

**Comment by surfsun** [comment]
删除.idea目录下的配置文件generator-config.xml 可以解决 
![config](https://user-images.githubusercontent.com/17524110/56630117-ae720380-6682-11e9-9986-a3e5306a2def.png)
