### ISSUE TITLE
建议改成每次生成时都需输入账号和密码

### ISSUE THREAD

**Issue by yulingao** [kmaster/better-mybatis-generator#32]
最近修改了mysql的密码之后，已经不能生成代码了。卸载或者重新启动idea都不能解决问题，因为没有输入密码的框出现了

**Comment by surfsun** [comment]
![image](https://user-images.githubusercontent.com/17524110/62350923-c76a3a80-b536-11e9-9d0f-18cd8e23d602.png)
项目.idea有保存数据库连接信息  删除此配置文件可以解决
