### ISSUE TITLE
出现 Generate Finish 后，文件没有创建

### ISSUE THREAD

**Issue by sunsteam** [kmaster/better-mybatis-generator#9]
IntelliJ IDEA 2018.3.1 (Ultimate Edition)
Build #IU-183.4588.61, built on December 4, 2018
Licensed to Yuxing Sun
Subscription is active until November 23, 2019
For educational use only.
JRE: 1.8.0_152-release-1343-b16 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.14.1

![image](https://user-images.githubusercontent.com/7489390/49794368-5b05b580-fd72-11e8-872b-0eb64005a37b.png)

各项操作都正常，但是出现如上的finish后，文件没有创建，也没报错。我测试了只能创建到 src/main/java 那层

IDEA 我已经卸载重装过了 也没解决问题 

考虑是否是权限问题，chmod 777 也没解决

**Comment by kmaster** [comment]
你用的应该是macOS 我目前没这个环境 没法调试找问题。我已经添加了些配置让代码下载后即可运行，你可以自己debug看看。估计是某个路径错误导致的。
![image](https://user-images.githubusercontent.com/17524110/49993700-53d4e680-ffc2-11e8-8d57-72a89307cf4f.png)

**Comment by PataPon-coder** [comment]
我也遇到这个问题 请问解决了吗 同是mac平台

**Comment by sunsteam** [comment]
> 我也遇到这个问题 请问解决了吗 同是mac平台

嗯 需要在数据库页面配置相符的scheme 然后刷新一下数据库连接
